// Canonical field map for Owner Surrender (required fields v1)
// Auto-generated by scripts/forms/normalize_required_labels_owner_surrender.py
export type OwnerSurrenderField = {
  key: string;
  label: string;
  required: boolean;
};

export const OWNER_SURRENDER_REQUIRED_FIELDS: OwnerSurrenderField[] = [
  { key: "acquisition-source", label: "Where did you acquire the dog?", required: true },
  { key: "chases", label: "Does this dog chase anything?", required: true },
  { key: "crate-trained", label: "Is the dog crate trained?", required: true },
  { key: "dog-age", label: "Dog's DOB /Approximate Age", required: true },
  { key: "dog-altered", label: "Is the dog spayed or neutered", required: true },
  { key: "dog-breed-type", label: "Is the dog a Great Dane or Great Dane Mix?", required: true },
  { key: "dog-gastropexied", label: "its stomach tacked?", required: true },
  { key: "dog-name", label: "Dog's Name / Nicknames", required: true },
  { key: "dog-sex", label: "Gender Male Female", required: true },
  { key: "dog-weight", label: "Dog's Weight", required: true },
  { key: "energy-level", label: "What level of energy does your dog have?", required: true },
  { key: "feeding-schedule", label: "How often do you feed the dog and how much do you feed them per meal?", required: true },
  { key: "heartworm-prevention", label: "Is this dog currently on heartworm prevention?", required: true },
  { key: "leash-behavior", label: "If taken on walks, how does the dog do on leash?", required: true },
  { key: "left-when-alone", label: "Where do you leave the dog when no one was home?", required: true },
  { key: "other-states", label: "state of residence? If so, where?", required: true },
  { key: "owner-name", label: "Owner's Name", required: true },
  { key: "owner-email", label: "Owner\'s Email", required: true },

  { key: "owner-phone-primary", label: "Owner's Preferred Contact Number", required: true },
  { key: "ownership-duration", label: "How long have you owned the dog?", required: true },
  { key: "play-preferences", label: "How does the dog like to play? (check all that apply)", required: true },
  { key: "prior-history", label: "What do you know of the dog's history prior to your own?", required: true },
  { key: "referral-source", label: "How did you hear about RMGDRI?", required: true },
  { key: "surgeries", label: "Has the dog ever required any surgeries?", required: true },
  { key: "vaccinations-current", label: "Is the dog current on vaccinations? (rabies and distemper/parvo)", required: true },
  { key: "vet-address", label: "Veterinary office address", required: true },
  { key: "vet-phone", label: "Veterinary office phone number", required: true },
  { key: "vet-yearly", label: "Has the dog seen a veterinarian at least once a year?", required: true },
  { key: "where-spends-time", label: "Where does the dog spend most of his/her time? (check all that apply)", required: true },
];

// Deterministic alias export for downstream imports
export const OWNER_SURRENDER_FIELD_MAP = OWNER_SURRENDER_REQUIRED_FIELDS;
export default OWNER_SURRENDER_FIELD_MAP;
