import type { MetadataRoute } from 'next'

/**
 * /robots.txt — generated by Next.js App Router metadata route.
 * Added by CC-PACKET-RMGD-001 SEO asset gate (2026-05-06).
 *
 * Canonical host: https://rmgreatdane.org
 *   - Override per-environment via NEXT_PUBLIC_SITE_URL.
 *   - Fallback hard-coded so previews / local builds still emit the production
 *     host in the sitemap reference (per packet spec).
 *
 * Disallow list mirrors the production middleware/auth surface:
 *   /admin       — passphrase-gated admin
 *   /api         — server route handlers (no SEO value, no public crawl)
 *   /auth        — Supabase auth flow
 *   /dashboard   — applicant dashboard (auth-required)
 *   /studio      — Sanity Studio embed
 */

const RAW_SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://rmgreatdane.org'
const SITE_URL = RAW_SITE_URL.replace(/\/$/, '')

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/admin', '/api', '/auth', '/dashboard', '/studio'],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  }
}
