import type { MetadataRoute } from 'next'
import { client } from '@/lib/sanity/client'
import { getAllRecords, getYears } from '@/lib/adoption-successes'

/**
 * /sitemap.xml — generated by Next.js App Router metadata route.
 * Added by CC-PACKET-RMGD-001 SEO asset gate (2026-05-06).
 *
 * Composition:
 *   1. Public static routes from src/app/(main)/<slug>/page.tsx
 *      (excludes /admin, /api, /auth, /dashboard, /studio, /apply form pages,
 *      /intake-pause, /[slug] dynamic, /successes/* in-app redirects,
 *      /the-dog-blog/[slug] (CR-A: known broken until route fixed).
 *   2. Sanity `page` documents resolved by /(main)/[slug]/page.tsx
 *      (skipped if slug collides with a static route or a private prefix).
 *   3. Available-dane detail URLs (Sanity `dog` documents, status filter
 *      mirrors src/app/(main)/available-danes/page.tsx).
 *   4. Adoption-success year archives + detail URLs (merged JSON + Sanity
 *      adopted dogs, via lib/adoption-successes).
 *
 * Canonical host: https://rmgreatdane.org (override via NEXT_PUBLIC_SITE_URL).
 *
 * Revalidation: hourly so Sanity content updates flow through within ~1h
 * without a full rebuild.
 */

export const revalidate = 3600

const RAW_SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://rmgreatdane.org'
const SITE_URL = RAW_SITE_URL.replace(/\/$/, '')

const PRIVATE_PREFIXES = ['/admin', '/api', '/auth', '/dashboard', '/studio']

type StaticRoute = {
  path: string
  priority: number
  changeFrequency: 'daily' | 'weekly' | 'monthly' | 'yearly'
}

const PUBLIC_STATIC_ROUTES: ReadonlyArray<StaticRoute> = [
  { path: '/', priority: 1.0, changeFrequency: 'weekly' },
  { path: '/about-great-danes', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/about-rmgdri', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/adopt-a-senior', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/adoption-application', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/adoption-information', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/adoption-successes', priority: 0.8, changeFrequency: 'weekly' },
  { path: '/available-danes', priority: 0.9, changeFrequency: 'daily' },
  { path: '/bite-report-human', priority: 0.5, changeFrequency: 'yearly' },
  { path: '/donate-to-rmgdri', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/events', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/foster-a-great-dane', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/foster-application', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/great-dane-health-care', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/our-board', priority: 0.5, changeFrequency: 'yearly' },
  { path: '/our-mission', priority: 0.5, changeFrequency: 'yearly' },
  { path: '/our-organization', priority: 0.5, changeFrequency: 'yearly' },
  { path: '/rehome-a-dane', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/shelter-transfers', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/sponsor-a-dane', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/surrender', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/the-dog-blog', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/volunteer', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/volunteer-opportunities', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/volunteer-survey', priority: 0.5, changeFrequency: 'yearly' },
]

function isPublicPath(path: string): boolean {
  return !PRIVATE_PREFIXES.some((p) => path === p || path.startsWith(p + '/'))
}

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const now = new Date()

  const staticEntries: MetadataRoute.Sitemap = PUBLIC_STATIC_ROUTES.map(
    ({ path, priority, changeFrequency }) => ({
      url: `${SITE_URL}${path}`,
      lastModified: now,
      changeFrequency,
      priority,
    })
  )
  const staticPathSet = new Set(PUBLIC_STATIC_ROUTES.map((r) => r.path))

  // Sanity `page` documents (resolved by (main)/[slug])
  let sanityPageEntries: MetadataRoute.Sitemap = []
  try {
    const pages = await client.fetch<Array<{ slug: string; _updatedAt: string }>>(
      `*[_type == "page" && defined(slug.current)] {
        "slug": slug.current,
        _updatedAt
      }`
    )
    sanityPageEntries = pages
      .filter((p) => {
        if (!p.slug) return false
        const fullPath = '/' + p.slug.replace(/^\//, '')
        return isPublicPath(fullPath) && !staticPathSet.has(fullPath)
      })
      .map((p) => ({
        url: `${SITE_URL}/${p.slug.replace(/^\//, '')}`,
        lastModified: new Date(p._updatedAt),
        changeFrequency: 'monthly' as const,
        priority: 0.6,
      }))
  } catch (err) {
    console.warn('[sitemap] failed to fetch Sanity pages:', err)
  }

  // Available-dane detail URLs (status filter mirrors the listing page query)
  let availableDaneEntries: MetadataRoute.Sitemap = []
  try {
    const dogs = await client.fetch<Array<{ slug: string; _updatedAt: string }>>(
      `*[_type == "dog"
          && status in ["available", "pending", "foster-needed", "waiting-transport", "under-evaluation", "medical-hold", "behavior-hold", "permanent-foster"]
          && hideFromWebsite != true
          && defined(slug.current)] {
        "slug": slug.current,
        _updatedAt
      }`
    )
    availableDaneEntries = dogs
      .filter((d) => d.slug && isPublicPath('/available-danes/' + d.slug))
      .map((d) => ({
        url: `${SITE_URL}/available-danes/${d.slug}`,
        lastModified: new Date(d._updatedAt),
        changeFrequency: 'weekly' as const,
        priority: 0.8,
      }))
  } catch (err) {
    console.warn('[sitemap] failed to fetch available danes:', err)
  }

  // Adoption-success year archives + detail URLs
  let successEntries: MetadataRoute.Sitemap = []
  try {
    const [years, records] = await Promise.all([getYears(), getAllRecords()])
    const yearEntries: MetadataRoute.Sitemap = years.map(({ year }) => ({
      url: `${SITE_URL}/adoption-successes/${year}`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    }))
    const detailEntries: MetadataRoute.Sitemap = records.map((r) => ({
      url: `${SITE_URL}/adoption-successes/${r.adoption_year}/${r.slug}`,
      lastModified: now,
      changeFrequency: 'yearly' as const,
      priority: 0.5,
    }))
    successEntries = [...yearEntries, ...detailEntries]
  } catch (err) {
    console.warn('[sitemap] failed to compose adoption successes:', err)
  }

  return [...staticEntries, ...sanityPageEntries, ...availableDaneEntries, ...successEntries]
}
